<?php

namespace AppBundle\Repository;

/**
 * UserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLogRepository extends \Doctrine\ORM\EntityRepository
{
}
