<?php

namespace Songbird\NestablePageBundle\Repository;

use Songbird\NestablePageBundle\Entity\Page;

/**
 * PageMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMetaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Page $page
     * @param $locale
     *
     * @return PageMeta
     */
    public function findPageMetaByLocale(Page $page, $locale) {

        $query = $this->createQueryBuilder('pm')
            ->where('pm.locale = :locale')
            ->andWhere('pm.page = :page')
            ->setParameter('locale', $locale)
            ->setParameter('page', $page)
            ->getQuery();

        return $query->getOneOrNullResult();

    }
}
